# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Termina 1
    init: echo 'before script'
    command: npm run dev
  - name: Terminal 2
    init: npm install 
    command: npm run dev
  - name: Terminal 3
    init: echo ' this is terminal 3'
    command: echo 'hello terminal 3'


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
